name: Commit Changes
description: Commit changes with a custom commit message
inputs:
  commit-message:
    description: Commit message
    required: false

runs:
  using: composite
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit changes
      shell: bash
      run: |
        git add .
        git commit -m "${{ inputs.commit-message }}"  # Use the input commit message
        git push origin main
