name: Commit Changes

on:
  workflow_call:
    inputs:
      commit_message:
        description: 'The commit message'
        required: true
        type: string

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Commit changes
      run: |
        git add .
        git commit -m "${{ inputs.commit_message }}"  # Use the input commit message
        git push origin main
