# https://medium.com/nerd-for-tech/use-a-swift-command-line-tool-in-a-github-workflow-69d0331886b1
name: SwiftFormat lint

on:
  workflow_call:
  
jobs:
  swiftformat:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache/Restore Mint packages
        id: mint-cache
        uses: actions/cache@v4
        with:
            path: ${{ github.workspace }}/mint
            key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
            restore-keys: ${{ runner.os }}-mint-
            
      - name: Upgrade or install Mint
        run: |
            brew upgrade mint || brew install mint || true
            
      - name: Install SwiftFormat (if not yet cached)
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap
        
      - name: Run SwiftFormat
        run: mint run swiftformat --verbose .
